q3bicycle:
	g++ q3bicycle.cpp -o q3bicycle -lglut -lGLU -lGL
	./q3bicycle


q2house:
	g++ q2house.cpp -o q2house -lglut -lGLU -lGL
	./q2house

q1tree:
	g++ q1tree.cpp -o q1tree -lglut -lGLU -lGL
	./q1tree

