
q1:
	g++ q1_Car_FloodFill_Bresenhem.cpp -o q1_Car_FloodFill_Bresenhem -lglut -lGLU -lGL
	./q1_Car_FloodFill_Bresenhem

q2:

	g++ q2_BusDrawing.cpp -o q2_BusDrawing -lglut -lGLU -lGL
	./q2_BusDrawing

ignore: 
	g++ floodfill.cpp -lglut -lGLU -lGL
	./a.out