q2bresen:
	g++ q2lineBresh.cpp -o q2lineBresh -lglut -lGLU -lGL
	./q2lineBresh


q3midpt:
	g++ q3lineMid.cpp -o q3lineMid -lglut -lGLU -lGL
	./q3lineMid

q1dda:
	g++ q1lineDDA.cpp -o q1lineDDA -lglut -lGLU -lGL
	./q1lineDDA